export default defineAppConfig({
  ui: {
    icons: {
      light: "mdi:white-balance-sunny",
      dark: "mdi:weather-night",
      menu: "mdi:menu",
      search: "mdi:magnify",
      close: "mdi:close",
      upload: "mdi:upload",
      arrowUp: "mdi:arrow-up",
      arrowDown: "mdi:arrow-down",
      arrowLeft: "mdi:arrow-left",
      arrowRight: "mdi:arrow-right",
      reload: "mdi:reload",
      loading: "mdi:loading",
      plus: "mdi:plus",
      minus: "mdi:minus",
      caution: "mdi:alert",
      check: "mdi:check",
      chevronDoubleLeft: "mdi:chevron-double-left",
      chevronDoubleRight: "mdi:chevron-double-right",
      chevronDown: "mdi:chevron-down",
      chevronLeft: "mdi:chevron-left",
      chevronRight: "mdi:chevron-right",
      chevronUp: "mdi:chevron-up",
      copy: "mdi:clipboard-multiple",
      copyCheck: "mdi:clipboard-check-multiple",
      drag: "mdi:drag",
      ellipsis: "mdi:dots-horizontal",
      error: "mdi:exclamation",
      external: "mdi:arrow-top-right",
      eye: "mdi:eye",
      eyeOff: "mdi:eye-off",
      file: "mdi:file",
      folder: "mdi:folder",
      folderOpen: "mdi:folder-open",
      info: "mdi:information",
      panelClose: "mdi:menu-close",
      panelOpen: "mdi:menu-open",
      stop: "mdi:stop",
      success: "mdi:check",
      warning: "mdi:exclamation",
    },
  },
});
