name: Supabase

on:
  schedule:
    - cron: "0 0 */3 * *"  
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -H "apikey: ${{ secrets.SUPABASE_SECRET_TOKEN }}" \
          https://akhxphgocxpyoofvdqwi.supabase.co/rest/v1/VehicleManufacturers?select=id
